config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :messages

  resources :styles do
    get 'about', on: :collection
  end

  resources :styles
  resources :beer_clubs
  resources :beers
  
  resources :memberships do
    post 'confirm', on: :member
  end

  resources :users do
    post 'toggle_activity', on: :member
    get 'recommendation', on: :member
  end
  get 'signup', to: 'users#new'
  
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  
  
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only: [:index, :show]
  # mikä generoi samat polut kuin seuraavat kaksi
  # get 'places', to: 'places#index'
  # get 'places/:id', to: 'places#show'
  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'

  get 'calculator', to: 'misc#calculator'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  after_create_commit do
    broadcast_prepend_to "messages_index", partial: "messages/message", target: "messages"
  end

  after_destroy_commit do
    broadcast_remove_to "messages_index"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[show edit update destroy]

  # GET /messages or /messages.json
  def index
    @messages = Message.all.reverse_order
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user

    respond_to do |format|
      if @message.save
        format.turbo_stream {
          render turbo_stream: turbo_stream.append("messages", partial: "message", locals: { message: @message })
        }
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.remove(@message)
      }
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).permit(:content, :user_id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :content %>

    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <%= link_to "X", message, data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"  },
                              class: "btn btn-danger" %>
    <strong><%= message.user.username %></strong>
    <%= message.content %>
    <%= message.created_at %>

  </p>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<%= turbo_stream_from "messages_index" %>

<p style="color: green"><%= notice %></p>

<h1>Messages</h1>
<%= turbo_frame_tag "new_message", src: new_message_path if current_user %>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
  <% end %>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>
<%= turbo_frame_tag "new_message" do %>
  <%= render "form", message: @message %>
<% end %>
<br>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>