config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :messages

  resources :styles do
    get 'about', on: :collection
  end

  resources :styles
  resources :beer_clubs
  resources :beers
  
  resources :memberships do
    post 'confirm', on: :member
  end

  resources :users do
    post 'toggle_activity', on: :member
    get 'recommendation', on: :member
  end
  get 'signup', to: 'users#new'
  
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  
  
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only: [:index, :show]
  # mikä generoi samat polut kuin seuraavat kaksi
  # get 'places', to: 'places#index'
  # get 'places/:id', to: 'places#show'
  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'

  get 'calculator', to: 'misc#calculator'
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_is_admin, only: [:destroy]

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when "name" then @beer_clubs.sort_by(&:name)
                  when "founded" then @beer_clubs.sort_by(&:founded)
                  when "city" then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @membership = Membership.new
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)
    respond_to do |format|
      @beer_club.save
      @membership = Membership.new(beer_club_id: @beer_club.id, user_id: current_user.id, confirmed: true)
      @membership.save
      if @beer_club.save && @membership.save
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <p>
    <strong>Name:</strong>
    <%= beer_club.name %>
  </p>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>

</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, { class: "form-label"} %>
    <%= form.text_field :name, { class: "form-control", placeholder: "Club Name" } %>
  </div>

  <div>
    <%= form.label :founded, { class: "form-label"} %>
    <%= form.number_field :founded, { class: "form-control", placeholder: "Founding Year" } %>
  </div>

  <div>
    <%= form.label :city, { class: "form-label"} %>
    <%= form.text_field :city, { class: "form-control", placeholder: "City" } %>
  </div>

  <div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>

<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club, class:"btn btn-show" %> |
  <%= link_to "Back to beer clubs", beer_clubs_path, class:"btn btn-secondary" %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>
Sort by: 
<%= link_to "Name", beer_clubs_path(order: "name")%>
<%= link_to "Year", beer_clubs_path(order: "founded")%>
<%= link_to "City", beer_clubs_path(order: "city")%>
<div id="beer_clubs">
  <% @beer_clubs.each do |beer_club| %>
    <%= render beer_club %>
    <p>
      <%= link_to "Show this beer club", beer_club, class:"btn btn-info" %>
    </p>
  <% end %>
</div>

<%= link_to('New beer club', new_beer_club_path, class:"btn btn-success") if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path, class:"btn btn-secondary" %>
</div>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<% if current_user&.get_membership(@beer_club)&.confirmed %> 
  <strong>Waiting confirmation</strong>
  <ul>
    <% @beer_club.users.each do |user| %>
      <% if !user.get_membership(@beer_club).confirmed %> 
        <li>
          <%= link_to user.username, user %>
          <%= link_to "Confirm", confirm_membership_path(user.get_membership(@beer_club).id), data: {turbo_method: "post"}, class:"btn btn-success" %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<div id="members">
  <strong>Members:</strong>
  <ul>
    <% @beer_club.users.each do |user| %>
      <% if user.get_membership(@beer_club).confirmed %> 
        <li><%= link_to user.username, user %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<% if current_user %>

  <% if current_user.beer_clubs.include?(@beer_club) %>
    <%= form_with(
      url: "/memberships/#{(current_user.get_membership(@beer_club)).id}", method: :delete) do |form| %>
      <%= form.submit "End the membership" %>
    <% end %>

  <% else %>
    <%= form_with(model: @membership) do |form| %>
      <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.submit "Join the beer club" %>
    <% end %>
  <% end %>

<% end %>
<%= edit_and_destroy_buttons(@beer_club) %>