config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :messages

  resources :styles do
    get 'about', on: :collection
  end

  resources :styles
  resources :beer_clubs
  resources :beers
  
  resources :memberships do
    post 'confirm', on: :member
  end

  resources :users do
    post 'toggle_activity', on: :member
    get 'recommendation', on: :member
  end
  get 'signup', to: 'users#new'
  
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  
  
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only: [:index, :show]
  # mikä generoi samat polut kuin seuraavat kaksi
  # get 'places', to: 'places#index'
  # get 'places/:id', to: 'places#show'
  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'

  get 'calculator', to: 'misc#calculator'
end

app/models/style.rb
class Style < ApplicationRecord
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  def self.top(num)
    sorted_by_rating_in_desc_order = Style.all.sort_by(&:average_rating)
    sorted_by_rating_in_desc_order.last(num).reverse
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: %i[show edit update destroy]

  # GET /styles or /styles.json
  def index
    # now this takes only care of the full page reloads
    @styles = Style.all
  end

  # own controller function for the partial
  def about
    render partial: 'about'
  end

  # GET /styles/1 or /styles/1.json
  def show
    return unless turbo_frame_request?

    render partial: 'details', locals: { style: @style }

    # the default is a full page reload
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles or /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to style_url(@style), notice: "Style was successfully created." }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1 or /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to style_url(@style), notice: "Style was successfully updated." }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1 or /styles/1.json
  def destroy
    @style.destroy

    respond_to do |format|
      format.html { redirect_to styles_url, notice: "Style was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_style
    @style = Style.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def style_params
    params.require(:style).permit(:name, :description)
  end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_about.html.erb
<%= turbo_frame_tag "about_style" do %>
  <p>About information</p>
<% end %>

app/views/styles/_details.html.erb
<%= turbo_frame_tag "style_details" do %>
  <h3><%= style.name %></h3>
  <p>
    <strong>Description:</strong>
    <%= style.description %>
  </p>

  <h4>beers</h4>

  <ul>
    <% @style.beers.each do |beer| %>
      <li>
        <%= link_to beer.name, beer %>
      </li>
    <% end %>
  </ul>  
<% end %>

app/views/styles/_form.html.erb
<%= form_with(model: style) do |form| %>
  <% if style.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
        <% style.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/styles/_style.html.erb
<div id="<%= dom_id style %>">
  <p>
    <strong>Name:</strong>
    <%= style.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= style.description %>
  </p>

</div>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render "form", style: @style %>

<br>

<div>
  <%= link_to "Show this style", @style, class:"btn btn-info" %> |
  <%= link_to "Back to styles", styles_path , class:"btn btn-secondary"%>
</div>

app/views/styles/index.html.erb
<h1>Styles</h1>

<div id="styles">
  <%= turbo_frame_tag "styles" do %>
    <% @styles.each do |style| %>
      <%= link_to style.name, style, data: { turbo_frame: "style_details" } %>
    <% end %>
  <% end %>

  <%= turbo_frame_tag "style_details" do %>
  <% end %>  
</div>

<%= link_to "New style", new_style_path, class:"btn btn-success" %>

<br><br>

<%= turbo_frame_tag "about_style" do %>
  <%= link_to "about", about_styles_path %>
<% end %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render "form", style: @style %>

<br>

<div>
  <%= link_to "Back to styles", styles_path , class:"btn btn-secondary"%>
</div>

app/views/styles/show.html.erb
<%= render @style %>

<div>
  <%= link_to "Back to styles", styles_path, class:"btn btn-secondary" %>

<%= edit_and_destroy_buttons(@style) %>
</div>