config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :messages

  resources :styles do
    get 'about', on: :collection
  end

  resources :styles
  resources :beer_clubs
  resources :beers
  
  resources :memberships do
    post 'confirm', on: :member
  end

  resources :users do
    post 'toggle_activity', on: :member
    get 'recommendation', on: :member
  end
  get 'signup', to: 'users#new'
  
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  
  
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only: [:index, :show]
  # mikä generoi samat polut kuin seuraavat kaksi
  # get 'places', to: 'places#index'
  # get 'places/:id', to: 'places#show'
  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'

  get 'calculator', to: 'misc#calculator'
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, presence: true
  validate :year_cannot_be_in_future, on: :create

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  def year_cannot_be_in_future
    return unless year > Date.today.year || year < 1040

    errors.add(:year, "can't be in the future or past")
  end

  def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.count}"
  end

  def restart
    self.year = 2022
    puts "changed year to #{year}"
  end

  def to_s
    name
  end

  def self.top(num)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by(&:average_rating)
    sorted_by_rating_in_desc_order.last(num).reverse
  end

  after_create_commit do
    rows_id = if active
                "active_brewery_rows"
              else
                "retired_brewery_rows"
              end

    count_id = if active
                 "active_count_id"
               else
                 "retired_count_id"
               end

    status = active ? "active" : "retired"
    count = active ? Brewery.active.count : Brewery.retired.count

    broadcast_append_to "breweries_index", partial: "breweries/brewery_row", target: rows_id
    broadcast_update_to "breweries_index", partial: "breweries/brewery_count", target: count_id,
                                           locals: { count:, status: }
  end
end

app/controllers/breweries_controller.rb
# frozen_string_literal: true

# comment
class BreweriesController < ApplicationController
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :active, :count_retired, :count_active, :retired]
  before_action :ensure_that_is_admin, only: [:destroy]

  # GET /breweries or /breweries.json
  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
  end

  # GET /breweries/1 or /breweries/1.json
  def show; end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit; end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)
    respond_to do |format|
      if @brewery.save
        format.turbo_stream {
          status = @brewery.active? ? "active" : "retired"
          count = @brewery.active? ? Brewery.active.count : Brewery.retired.count
          render turbo_stream: [
            turbo_stream.append("#{status}_brewery_rows", partial: "brewery_row", locals: { brewery: @brewery }),
            turbo_stream.update("#{status}_count_id", partial: "brewery_count", locals: { count:, status: })
          ]
        }
        format.html { redirect_to brewery_url(@brewery), notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  def active
    render partial: 'brewery_list', locals: { breweries: Brewery.active, status: "active" }
  end

  def retired
    render partial: 'brewery_list', locals: { breweries: Brewery.retired, status: "retired" }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
# frozen_string_literal: true

# comment
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<div id="<%= dom_id brewery %>">
  <p>
    <h4>
      <strong><%= link_to brewery.name, brewery, data: { turbo_frame: "_top"} %></strong>
    </h4>
    <i> Established at <%= brewery.year %> </i>
    <% if not brewery.active  %>
      <span class="badge bg-secondary">retired</span>
    <% end %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= brewery.year %>
  </p>
  <p>
    Number of beers: <%= brewery.beers.count %>
  </p>
  <p>
    <% brewery.beers.each do |beer| %>
      <%= link_to beer.name, beer, data: { turbo_frame: "_top"} %>
    <% end %>
  </p>

  <p>
    <% if brewery.ratings.empty? %>
      brewery has not yet been rated!
    <% else %> 
      Beer has <%= pluralize(brewery.ratings.count, 'rating') %>
      with an average of <%= brewery.average_rating %> 
    <% end %>
  </p>
</div>

app/views/breweries/_brewery_count.html.erb
<%= turbo_frame_tag  status+"_count_tag" do %>
    Number of <%= status %> breweries
    <%= count %>
<% end %>

app/views/breweries/_brewery_list.html.erb
<%= turbo_frame_tag  status+"_breweries_tag" do %>
<table class="table table-hover">
  <thead>
    <th>Name</th>
    <th>year</th>
    <th>count</th>
    <th>rating</th>
  </thead>
  <tbody id="<%= status %>_brewery_rows">
    <% breweries.each do |brewery| %>
      <%= render "brewery_row", brewery: brewery %>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/breweries/_brewery_row.html.erb
<tr id="<%= dom_id(brewery) %>">
  <td><%= link_to brewery.name, brewery, data: { turbo_frame: "_top"} %></td>
  <td><%= brewery.year %></td>
  <td><%= brewery.beers.count %></td>
  <td><%= round(brewery.average_rating) %></td>
</tr>

app/views/breweries/_form.html.erb
<div data-controller="newbrew">
  <%= form_with(model: brewery, data: { action: "turbo:submit-end->newbrew#reset" }) do |form| %>
    <% if brewery.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

        <ul>
          <% brewery.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, data: { "newbrew-target": "name" } %>
    </div>

    <div>
      <%= form.label :year, style: "display: block" %>
      <%= form.number_field :year, data: { "newbrew-target": "year" } %>
    </div>

    <div>
      <%= form.label :active, style: "display: block" %>
      <%= form.check_box :active, data: { "newbrew-target": "active" } %>
    </div>
    
    <% if current_user %>
      <button data-action="click->newbrew#reset">Reset</button>
    <% end %>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<div>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery, class:"btn btn-info" %> |
  <%= link_to "Back to breweries", breweries_path , class:"btn btn-secondary"%>
</div>

app/views/breweries/index.html.erb
<%= turbo_stream_from "breweries_index" %>

<h1>Breweries</h1>
<p> Number of breweries: <%= @active_breweries.count + @retired_breweries.count %> </p>

<h2>Active</h2>
<div id= "active_count_id">
  <%= render "brewery_count", status: "active", count: @active_breweries.count %>
</div>
<%= turbo_frame_tag "active_breweries_tag", src: active_breweries_path do %>
    Finding active breweries...
<% end %>

<h2>Retired</h2>
<div id= "retired_count_id">
    <%= render "brewery_count", status: "retired", count: @retired_breweries.count %>
</div>
<%= turbo_frame_tag "retired_breweries_tag", src: retired_breweries_path do %>
    Finding retired breweries...
<% end %>

<p>
  <%=link_to 'list of beers', beers_path, class:"btn btn-secondary" %>
</p>
<%= turbo_frame_tag "new_brewery", src: new_brewery_path if current_user %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>
<%= turbo_frame_tag "new_brewery" do %>
  <%= render "form", brewery: @brewery %>
<% end %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path, class:"btn btn-secondary" %>
</div>

app/views/breweries/panimot.html.erb
 panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<%= render @brewery %>
<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), data: {turbo_method: "post"}, class: "btn btn-primary" %>

<div>
  <%= link_to "Back to breweries", breweries_path, class:"btn btn-secondary" %>
  <% if current_user %>
    <%= edit_and_destroy_buttons(@brewery) %>
  <% end %>
  <p>
    <%=link_to 'list of beers', beers_path, class:"btn btn-secondary" %>
  </p>
</div>